try {
    coreutils --help > $null

    function arch { coreutils arch @args }
    function b2sum { coreutils b2sum @args }
    function b3sum { coreutils b3sum @args }
    function base32 { coreutils base32 @args }
    function base64 { coreutils base64 @args }
    function basename { coreutils basename @args }
    function basenc { coreutils basenc @args }
    function cat { coreutils cat @args }
    function cksum { coreutils cksum @args }
    function comm { coreutils comm @args }
    function cp { coreutils cp @args }
    function csplit { coreutils csplit @args }
    function cut { coreutils cut @args }
    function date { coreutils date @args }
    function dd { coreutils dd @args }
    function df { coreutils df @args }
    function dir { coreutils dir @args }
    function dircolors { coreutils dircolors @args }
    function dirname { coreutils dirname @args }
    function du { coreutils du @args }
    function echo { coreutils echo @args }
    function env { coreutils env @args }
    function expand { coreutils expand @args }
    function expr { coreutils expr @args }
    function factor { coreutils factor @args }
    function false { coreutils false @args }
    function fmt { coreutils fmt @args }
    function fold { coreutils fold @args }
    function hashsum { coreutils hashsum @args }
    function head { coreutils head @args }
    function hostname { coreutils hostname @args }
    function join { coreutils join @args }
    function link { coreutils link @args }
    function ln { coreutils ln @args }
    function ls { coreutils ls @args }
    function md5sum { coreutils md5sum @args }
    function mkdir { coreutils mkdir @args }
    function mktemp { coreutils mktemp @args }
    function more { coreutils more @args }
    function mv { coreutils mv @args }
    function nl { coreutils nl @args }
    function nproc { coreutils nproc @args }
    function numfmt { coreutils numfmt @args }
    function od { coreutils od @args }
    function paste { coreutils paste @args }
    function pr { coreutils pr @args }
    function printenv { coreutils printenv @args }
    function printf { coreutils printf @args }
    function ptx { coreutils ptx @args }
    function pwd { coreutils pwd @args }
    function readlink { coreutils readlink @args }
    function realpath { coreutils realpath @args }
    function rm { coreutils rm @args }
    function rmdir { coreutils rmdir @args }
    function seq { coreutils seq @args }
    function sha1sum { coreutils sha1sum @args }
    function sha224sum { coreutils sha224sum @args }
    function sha256sum { coreutils sha256sum @args }
    function sha3-224sum { coreutils sha3-224sum @args }
    function sha3-256sum { coreutils sha3-256sum @args }
    function sha3-384sum { coreutils sha3-384sum @args }
    function sha3-512sum { coreutils sha3-512sum @args }
    function sha384sum { coreutils sha384sum @args }
    function sha3sum { coreutils sha3sum @args }
    function sha512sum { coreutils sha512sum @args }
    function shake128sum { coreutils shake128sum @args }
    function shake256sum { coreutils shake256sum @args }
    function shred { coreutils shred @args }
    function shuf { coreutils shuf @args }
    function sleep { coreutils sleep @args }
    function sort { coreutils sort @args }
    function split { coreutils split @args }
    function sum { coreutils sum @args }
    function sync { coreutils sync @args }
    function tac { coreutils tac @args }
    function tail { coreutils tail @args }
    function tee { coreutils tee @args }
    function test { coreutils test @args }
    function touch { coreutils touch @args }
    function tr { coreutils tr @args }
    function true { coreutils true @args }
    function truncate { coreutils truncate @args }
    function tsort { coreutils tsort @args }
    function uname { coreutils uname @args }
    function unexpand { coreutils unexpand @args }
    function uniq { coreutils uniq @args }
    function unlink { coreutils unlink @args }
    function vdir { coreutils vdir @args }
    function wc { coreutils wc @args }
    function whoami { coreutils whoami @args }
    function yes { coreutils yes @args }
} catch { }
